name: Blacksmith
on: [push]
jobs:
  Blacksmith-Runner:
    runs-on:
      - blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Fix chalk compatibility
        run: npm install chalk@4.1.2 --save-exact
      
      - name: Install @limetest/limetest
        run: npm install @limetest/limetest
      
      - name: Run Limetest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npx limetest